const express = require('express');
const cors = require('cors');
const { exec } = require('child_process');
const fs = require('fs');
const path = require('path');

const app = express();
const PORT = process.env.PORT || 5000;

app.use(cors());
app.use(express.json());

// Simulasi penyimpanan file berkas video hasil ekspor
const EXPORT_DIR = path.join(__dirname, 'exported');
if (!fs.existsSync(EXPORT_DIR)){
    fs.mkdirSync(EXPORT_DIR);
}

// Menyajikan file statis ekspor video
app.use('/exported', express.static(EXPORT_DIR));

/**
 * 1. ENDPOINT: MEMINTA AI MENGHASILKAN KODE (Sesuai ide prompt)
 * Menggunakan direct request atau SDK resmi Gemini 2.5/3.5
 */
app.post('/api/generate-code', async (req, res) => {
    const { prompt } = req.body;

    if (!prompt) {
        return res.status(400).json({ error: 'Prompt tidak boleh kosong.' });
    }

    try {
        console.log(`[Gemini AI] Memproses pembuatan kode untuk konsep: "${prompt}"`);
        
        // Di aplikasi nyata, lakukan call API Gemini:
        // const response = await fetch("https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash:generateContent?key=" + PROCESS.ENV.GEMINI_API_KEY ...);
        
        // Simulasi pengembalian kode HTML5 JS Canvas premium looping microstock automatik:
        const generatedCode = `// Autogenerated loop: ${prompt}
const canvas = document.getElementById('canvas');
const ctx = canvas.getContext('2d');
let time = 0;

function draw() {
    ctx.fillStyle = '#010515';
    ctx.fillRect(0, 0, canvas.width, canvas.height);
    
    // Grid sirkuit tekno berputar
    ctx.strokeStyle = 'rgba(0, 255, 204, 0.4)';
    ctx.lineWidth = 1.5;
    ctx.save();
    ctx.translate(canvas.width / 2, canvas.height / 2);
    ctx.rotate(time * 0.1);
    
    for (let r = 50; r < 500; r += 50) {
        ctx.beginPath();
        ctx.arc(0, 0, r, 0, Math.PI * 2 * (0.5 + 0.5 * Math.sin(time + r)));
        ctx.stroke();
    }
    ctx.restore();

    // Loop teks generator informasi
    ctx.fillStyle = '#ffffff';
    ctx.font = 'bold 36px monospace';
    ctx.textAlign = 'center';
    ctx.shadowColor = '#00ffcc';
    ctx.shadowBlur = 10;
    ctx.fillText("MEYDIAI CORE ENGINE", canvas.width / 2, canvas.height / 2 + 100);
    ctx.shadowBlur = 0;

    time += 0.01;
    requestAnimationFrame(draw);
}
draw();`;

        return res.status(200).json({ code: generatedCode });
    } catch (e) {
        console.error(e);
        return res.status(500).json({ error: 'Gagal menghubungkan ke AI Engine.' });
    }
});

/**
 * 2. ENDPOINT: PROSES EXPORT CANVAS MENJADI MP4 (Remotion / Headless browser + FFmpeg)
 * Algoritma backend nyata:
 * - Render Canvas di browser headless (misalnya Puppeteer) secara frame-by-frame.
 * - Ambil screenshot frame setiap durasi tertentu (60fps, misal 10 detik = 600 frame).
 * - Gabungkan 600 frame PNG tersebut menjadi MP4 looping menggunakan package fluent-ffmpeg.
 */
app.post('/api/render', async (req, res) => {
    const { code, format, duration } = req.body; // format '16:9' atau '9:16', durasi dlm detik

    if (!code) {
        return res.status(400).json({ error: 'Kode Canvas tidak terdeteksi untuk dirender.' });
    }

    const videoId = `video_${Date.now()}`;
    const outputFilename = `${videoId}.mp4`;
    const outputPath = path.join(EXPORT_DIR, outputFilename);

    console.log(`[Renderer] Memulai kompilasi rendering video ID: ${videoId} (${duration || 5}s dlm rasio ${format || '16:9'})`);

    try {
        // --- PROSES SIMULASI MERENDER ---
        // Jika aslinya menggunakan Puppeteer & FFmpeg, perintahnya seperti:
        // exec(`ffmpeg -framerate 60 -i frame_%d.png -c:v libx264 -pix_fmt yuv420p ${outputPath}`)
        
        // Kita mensimulasikan penulisan file mp4 tiruan agar API berfungsi secara penuh
        setTimeout(() => {
            console.log(`[Renderer] Berhasil menggabungkan video frame-by-frame ke format MP4.`);
            
            // Menulis dummy metadata video log
            fs.writeFileSync(`${outputPath}.log`, `Video render selesai pada ${new Date().toISOString()}`);

            // Mengirim response URL download video hasil ekspor
            // localhost di bawah diganti dengan IP/Domain cloud function atau server production Anda
            const downloadUrl = `http://localhost:${PORT}/exported/${outputFilename}`;
            
            return res.status(200).json({
                success: true,
                videoId: videoId,
                downloadUrl: downloadUrl,
                message: "Video Render dan Ekspor Berhasil diselesaikan."
            });
        }, 4000); // Simulasi delay proses render render sirkuit FFmpeg 4 detik

    } catch (err) {
        console.error("Renderer Error:", err);
        return res.status(500).json({ error: 'Gagal menyelesaikan render video otomatis.' });
    }
});

app.listen(PORT, () => {
    console.log(`========== MeydiAi Backend Running On Port ${PORT} ==========`);
    console.log(`Render Engine: http://localhost:${PORT}`);
    console.log(`Status: Docker & FFmpeg Ready`);
});
